language: java
cache:
  directories:
  - $HOME/.m2
services:
  - docker
jobs:
  include:
    - stage : test
    - stage : integration
      before_script:
        - docker run --name blazegraph -d -p 9999:9999 nawer/blazegraph:2.1.1
        - sleep 60
        - docker ps | grep blazegraph
        - curl http://localhost:9999/bigdata/#query
        - wget http://localhost:9999/blazegraph/namespace/kb/sparql
        - mvn package
        - cd engine/target
        - mv endpoints/endpoint-blazegraph.jpar endpoint.jpar
        - java -jar engine-0-SNAPSHOT.jar > log.txt &
        - sleep 30
        - cd ../..
      script:
        - mvn verify
    - stage : deploy
